# Generated by Django 5.1.5 on 2025-04-15 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HCProduct", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="productDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_meatcut",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "product_weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "product_packaging",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "product_origin",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "product_processing",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="HCProduct.product",
                    ),
                ),
            ],
        ),
    ]
