# Generated by Django 5.1.5 on 2025-04-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HCProduct", "0002_productdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=100, null=True
            ),
        ),
    ]
