# Generated by Django 5.1.5 on 2025-04-15 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HCProduct", "0003_product_product_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("discount_start_date", models.DateTimeField(blank=True, null=True)),
                ("discount_end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "discount_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "discount_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="HCProduct.product",
                    ),
                ),
            ],
        ),
    ]
