# Generated by Django 5.1.5 on 2025-03-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HCUser", "0003_shippingaddress"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homechoiceuser",
            options={"ordering": ["-date_joined"]},
        ),
    ]
