# Generated by Django 5.1.5 on 2025-03-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HCUser", "0004_alter_homechoiceuser_options"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="homechoiceuser",
            managers=[],
        ),
    ]
