# Generated by Django 5.1.5 on 2026-02-11 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HCUser", "0006_homechoiceuser_contact_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homechoiceuser",
            name="contact_number",
            field=models.CharField(
                blank=True,
                help_text="Kenyan contact number starting with +254.",
                max_length=13,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Contact number must start with +254 and be 13 digits total.",
                        regex="^\\+254\\d{9}$",
                    )
                ],
            ),
        ),
    ]
