# Generated by Django 5.1.5 on 2025-10-28 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HCOrder", "0002_payment_order_payment"),
        ("HCProduct", "0004_productdiscount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="order_price",
            new_name="total_amount",
        ),
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="HCOrder.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="HCProduct.product",
                    ),
                ),
            ],
        ),
    ]
