# Generated by Django 5.1.5 on 2026-02-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HCOrder", "0006_orderitem_weight_variant_apilog"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
